### ISSUE TITLE
fix integration test

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/aclib#1]
` [ACLibTests]     FAILED: ACLIB failed to verify JWE with payload compression... `

**Comment by syc17** [comment]
fixed, removed harded recipient's deviceID from the jwe request, replaced with the correct local variable.
`[root@stfc-tests tests]# ./aclib.sh
 Tester needs privilege to run Docker commands...
 Tests will be aborted if Agent does not have the necessary mF2C cedentials...
 [ACLibTests]     Starting...
Extracting container id ....
Checking if agent credentials exist....
Setting ACLib IP...
network id: mf2c_default
ALib host ip set to 192.168.176.23
 [ACLibTests]     SUCCESS: Got JWT from ACLib
 [ACLibTests]     SUCCESS:  [CIMI] cloud-entry-point exists
 [ACLibTests]     SUCCESS:  [CIMI] successfully pushed new session template for JWT tokens
 [ACLibTests]     SUCCESS:  [CIMI] successful login with JWT token
 [ACLibTests]     SUCCESS:  [CIMI] deleted JWT session template
 [ACLibTests]     SUCCESS: JWT verified by ACLib
The payload: a top secret message!
 [ACLibTests]     SUCCESS: JWS created by ACLib
verified JWS payload: a top secret message!
 [ACLibTests]     SUCCESS: JWS verfied by ACLib
 [ACLibTests]     SUCCESS: JWE with payload compression created by ACLib
verified JWE payload: a top secret message!
 [ACLibTests]     SUCCESS: JWE with payload compression verfied by ACLib
End of ACLib Tests.....
`
